name: simple_messenger_pro
description: A professional real-time messenger app built with Clean Architecture.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Architecture & DI
  image_picker: ^1.0.7
  get_it: ^7.6.0
  provider: ^6.1.1
  equatable: ^2.0.5 # Для сравнения объектов в Domain слое

  # Backend
  supabase_flutter: ^2.3.0 # Официальный клиент
  flutter_dotenv: ^5.1.0 # Безопасность

  cached_network_image: ^3.3.1

  # UI Utils
  intl: ^0.19.0 # Для форматирования дат сообщений
  google_fonts: ^6.1.0 # Чтобы было красиво

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1 # Если будем генерить модели
  

# ... (твои зависимости выше не трогай)

flutter:
  uses-material-design: true

  assets:
    - .env